### ISSUE TITLE
Extract Webview provider to a separate npm package

### ISSUE THREAD

**Issue by juliancwirko** [multiversx/mx-sdk-dapp#1024]
Can the Webview provider be extracted to a separate npm library? If not, what are the reasons?

It would be good to use it like we do with signing providers.

**Comment by CiprianDraghici** [comment]
Hey @juliancwirko , yes, will be extracted. For the moment our target is to have it into sdk-dapp because most of the dApps are using sdk-dapp. We intend to extract the provider in a separate repo, but I don't have an ETA
