### ISSUE TITLE
Login & logout fail 

### ISSUE THREAD

**Issue by JerbyIchrak** [multiversx/mx-sdk-dapp#221]
Hello, I found two issues that happens frequently:

**1-** The logout function does not work most of the time, it does clear the localStorage and sessionStorage, but then when we try to signin with another web wallet, we reach the elrond site but we are redirected back immediately with the same wallet we logged out with. 

***Logout impelementation:
```
import { logout} from "@elrondnetwork/dapp-core";

 const logOut = () => {
    logout(`${window.location.origin}/`);
    dispatch({ type: "logout" });
  };
```

**2-** The login fails in some cases, especially after the scenario of the failed logout, after redirection from elrond web wallet connect, we get redirected back with the address in the url, but the important store: persist:dapp-core-store is empty in the localStorage.
This store contains important login infos such as the connected address and the exact balance. Which leads us to a bug while trying to make a transaction, the dapp-core package will find a null balance, so the transaction redirection is blocked with a popup that tells "Insufficient EGLD funds" as the screenshot shows. 
![image](https://user-images.githubusercontent.com/44734357/167874020-a736c3c4-db6f-489c-bd5f-e503c3d69f5d.png)

***Login impelementation:
```
import { DappUI } from "@elrondnetwork/dapp-core";

const {
    ExtensionLoginButton,
    WebWalletLoginButton,
    LedgerLoginButton,
    WalletConnectLoginButton,
  } = DappUI;

            <div className="auth-buttons-container">
                  <WalletConnectLoginButton
                    callbackRoute={"/auth"}
                    logoutRoute="/"
                  />
                  <ExtensionLoginButton
                    callbackRoute={"/auth"}
                    logoutRoute="/"
                  />
                  <WebWalletLoginButton
                    callbackRoute={"/auth"}
                  />
                  <LedgerLoginButton
                    callbackRoute={"/auth"}
                  />
             </div>
```

**** Packages versions :  
    "react": "^17.0.2",
    "@elrondnetwork/dapp-core": "1.1.21",
    "@elrondnetwork/erdjs": "10.2.4",

*** Environment:
  windows 10 
  found it frequently on **chrome** and sometimes on firefox

**Comment by StanislavSava** [comment]
The problem could be caused by incomptabilities between erdjs versions. We are currently in the process of migrating dapp-core to erdjs 10, but 1.1.21 uses erdjs 9.1.0, so I think this could cause the issue. Can you try with erdjs 9.1.0?

**Comment by dotmobo** [comment]
Same here, i downgraded to erdjs 9.1.0 too

**Comment by abayoudh** [comment]
Hello ! we tested out the new release, 2.0.0-alpha.2, and unfortunately the issues persist !

**Comment by StanislavSava** [comment]
Does this happen with web wallet only? Do you have any errors in the web wallet console? How does the callback Url look like, when calling logout?

**Comment by StanislavSava** [comment]
There have been a lot of fixes related to this on the web wallet, can you try now?

**Comment by abayoudh** [comment]
Hello @StanislavSava! we tested out the new release of @elrondnetwork/dapp-core version 1.3.8 and the
@elrondnetwork/erdjs package version 10.2.7 in our project and in another new react project, we found this issues:
1- The initial login issue persists
2- The logout function does not work, the user can't logout from the first
try! it works from the second try!
3- Uncaught ReferenceError: process is not defined ,reported in this issue
https://github.com/ElrondNetwork/dapp-template/issues/45

**Comment by CiprianDraghici** [comment]
@abayoudh `dapp-core 1.x` is not compatible with `erdjs 10.x `. Please use latest `dapp-core 2.0.0-beta` and latest erdjs. Let us know your result. Thanks!

**Comment by abayoudh** [comment]
Hello, i try to use the dapp-core release 2.0.0-beta.11 and the new release 11.0.0, to resolve the issue, when i try to import the package, i face this issue 
![image](https://user-images.githubusercontent.com/107246993/182317633-958d4370-e568-4b09-a843-2f777b6f5bdd.png)

and when i change the import of DappProvider and DappUI like that 

import { DappProvider } from '@elrondnetwork/dapp-core/wrappers/DappProvider';
import * as DappUI from '@elrondnetwork/dapp-core/UI';

the DappProvider showing an error 
![image](https://user-images.githubusercontent.com/107246993/182318020-a0204ed6-8d7b-4e6c-b930-b8462d3786c6.png)

**Comment by CiprianDraghici** [comment]
@abayoudh Could you tell us what kind of error? Please display all the properties that you are trying to pass to the DappProvider component and hover the <DappProvider> tag to see the error.

**Comment by abayoudh** [comment]
Hello @CiprianDraghici, after testing the new release dapp-core release 2.0.0-beta.11
and the new release erdjs 11.0.0, the issues of logout and login fix it!

But we found other issue exiting in the Maiar app!
When I disconnected from our marketplace using the button in the Maiar mobile application and
reconnected again using another account, the system kept the details of the previous account.

Steps
1-    I connected to the marketplace using the Maiar mobile application
2-    I disconnected from the marketplace using the button in the Maiar mobile application
3-    I reconnected a second time using another account (.pem)

**Comment by CiprianDraghici** [comment]
> Hello @CiprianDraghici, after testing the new release dapp-core release 2.0.0-beta.11 and the new release erdjs 11.0.0, the issues of logout and login fix it!
> 
> But we found other issue exiting in the Maiar app! When I disconnected from our marketplace using the button in the Maiar mobile application and reconnected again using another account, the system kept the details of the previous account.
> 
> Steps 1- I connected to the marketplace using the Maiar mobile application 2- I disconnected from the marketplace using the button in the Maiar mobile application 3- I reconnected a second time using another account (.pem)

Hello @abayoudh, did you try the latest version ?
Could you tell us if is still reproducible ?

**Comment by CiprianDraghici** [comment]
Closed due to inactivity
