### ISSUE TITLE
Maiar Login Issue

### ISSUE THREAD

**Issue by rarescioroga** [multiversx/mx-sdk-dapp#296]
When I try to login using my Maiar App in the application I get this erro
![Screenshot 2022-06-30 at 12 21 30](https://user-images.githubusercontent.com/56501840/176641818-477910ac-8b2f-400d-afcd-5be327a6151f.png)

It happens when I navigate to the unlock page, however logging  in through the extension works correctly.
These are my dependecies
`{
"@elrondnetwork/dapp-core": "2.0.0-alpha.10",
    "@elrondnetwork/erdjs": "10.2.5",
    "@elrondnetwork/erdjs-network-providers": "0.1.5",
}`

I've tried different combinations of the latest version, but nothing seems to be solving this issue.

**Comment by theejkb** [comment]
I have another problem with Maiar App 
![image](https://user-images.githubusercontent.com/45352533/176891087-c0e9b6da-d07d-453e-9e6d-93083b6aabcc.png)

I think it's because I still use old version of dapp-core.

**Comment by cipriandraghici93** [comment]
HI!
This this:
- use ` 2.0.0-alpha.18` version,
- remove your node_modules and package-lock.json / yarn.lock file 
- clean install
- clear your sessionStorage and localStorage
- try again.

**Comment by CiprianDraghici** [comment]
@rarescioroga Please use the latest dapp-core beta version and let us know if is still reproducible. Also, please upgrade all the @elrondnetwork packages to the latest versions. Before testing, please clear your localStorage and sessionStorage.

**Comment by dan-merlea** [comment]
This happens to me also using

"@elrondnetwork/dapp-core": "^2.1.2",
"@elrondnetwork/erdjs": "^11.1.1",

<img width="794" alt="Screen Shot 2022-10-31 at 10 33 07" src="https://user-images.githubusercontent.com/3791777/198976884-ea8cd357-446e-44a0-a3f0-fa9a11f17418.png">

**Comment by CiprianDraghici** [comment]
@dan-merlea Could you attach some code snippets or a link to a reproducible repo?

**Comment by dan-merlea** [comment]
Sure!

index.tsx

```
<BrowserRouter>
	<DappProvider environment={network.id} customNetworkConfig={network}>
		<CoreContextProvider api={api}>
			<TransactionsToastList successfulToastLifetime={5000} className="" />
			<SignTransactionsModals />
			<RoomContextProvider>
				<App />
			</RoomContextProvider>
		</CoreContextProvider>
	</DappProvider>
</BrowserRouter>
```

Then I use the buttons ( eg: ExtensionLoginButton, WebWalletLoginButton ) and custom WalletConnectLoginContainer & LedgerLoginContainer for connection. These work fine.

Connection with Browser extension works ok even with this error.

**Comment by CiprianDraghici** [comment]
Please check this repo: https://github.com/ElrondNetwork/dapp-template
There is an example of dApp containing all login methods. If you still get this error after that, you should provide us a repo where the issue is reproducible.

**Comment by dan-merlea** [comment]
I was aware of the repo. I will try to strip down the code into a small repo with a reproducible issue. Thank you for quick reply!

**Comment by arhtudormorar** [comment]
We have checked your repo and It seems the issue is related to your project setup. We made the same steps in dapp-template, where the issue is not present. So please use [dapp-template](https://github.com/ElrondNetwork/dapp-template) as a starting point for your project.

**Comment by dan-merlea** [comment]
I will do that, but I don't think this should be the solution. The framework should be more flexible to the setup, especially since you can now debug the issue. Thank you for investigating!

**Comment by dan-merlea** [comment]
Ok, after some more investigation, found the issue! 
Wrap the dapp-template in <React.StrictMode></React.StrictMode>

https://reactjs.org/docs/strict-mode.html

**Comment by CiprianDraghici** [comment]
Please use the latest `sdk-dapp` version. If the issue persists, please create a new issue.
