### ISSUE TITLE
Maiar App & Defi Wallet Logout Issues

### ISSUE THREAD

**Issue by abayoudh** [multiversx/mx-sdk-dapp#412]
Hello, I found two issues tAfter upgrade to the new release dapp-core 2.0.1
and the new release erdjs 11.0.0, I found two issues that happens frequently 

The logout function does not work most of the time, especially when i use the Maiar App and the 
Defi wallet,
 
For the Maiar App, When I disconnected from our marketplace using the button in the Maiar mobile application and
reconnected again using another account, the system kept the details of the previous account, and 
the function logout doesn't redirect to the callback Url passed to!

For the Defi wallet, the callback Url not working most of the time 

---Environment:
Windows 10
Browsers: Chrome/Firefox

**Comment by arhtudormorar** [comment]
Hi! If you make an upgrade to version `2.0.2` do you still get the same behaviour?

**Comment by CiprianDraghici** [comment]
Could you check the latest version? We have used this package in a lot of dApps and didn't see this kind of behavior. Please let us know if the issue still persists. Also, if the issue is still reproducible, please create a repo with your scenario and let us investigate.

**Comment by CiprianDraghici** [comment]
Closed due to inactivity
