### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by AugustinVincent** [multiversx/mx-sdk-dapp#520]
Hello,

I get this error when i import module 
SyntaxError: Cannot use import statement outside a module

I'm using dapp-core version 1.27 with NextJsfew months now but I need to upgrade to dapp-core 2.x.x for the AxiosInterceptorContext package.

I heard that dapp-core doesn't work really well with NextJs but this kind of problem is really annoying. Next js is build on top of React and it should work as well with NextJs.

This error pop on every imports that I make from dapp-core.

```js
import { SignTransactionsModals, NotificationModal } from '@elrondnetwork/dapp-core/UI'; 
import { DappProvider, AxiosInterceptorContext // using this is optional } from '@elrondnetwork/dapp-core/wrappers';
```

package.json
```json
{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@elrondnetwork/dapp-core": "^2.2.3",
    "axios": "^0.27.2",
    "bignumber": "^1.1.0",
    "jsonwebtoken": "^8.5.1",
    "next": "12.2.3",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-modal": "^3.15.1"
  },
  "devDependencies": {
    "eslint": "8.20.0",
    "eslint-config-next": "12.2.3"
  }
}
```

Even one import cause this problem, there is nothing more to provide, I tried only one import, many paths, calling them in the code or not it's the same

Anyone has a solution, some config to change to make it work ?

**Comment by CiprianDraghici** [comment]
Please check this dApp template
https://github.com/multiversx/mx-template-nextjs-dapp

**Comment by CiprianDraghici** [comment]
Closed due to inactivity
