### ISSUE TITLE
logs erros and warnings with @walletconnect and others packages

### ISSUE THREAD

**Issue by Mandy9943** [multiversx/mx-sdk-dapp#521]
when I run my app with dapp-core and I see the console, I find a lot of errors and warnings but the app dont crash. The app runs without problems but there is a lot of errors in console. The easiest way to reproduce this, is to clone dapp-template from elrond and run npm start or yarn start. I add an image from my console.

![image](https://user-images.githubusercontent.com/74042888/209260142-7d00c9a8-2d03-471d-8d69-3f10e49343f4.png)

**Comment by CiprianDraghici** [comment]
Warnings are related to `@walletconnect` package. Under investigation but with a low priority as this is not a blocker.
