### ISSUE TITLE
Login with Maiar Extension not working

### ISSUE THREAD

**Issue by yankydoo** [multiversx/mx-sdk-dapp#524]
When trying to log in with the Maiar extension, I'm getting the following error:
```
chunk-GUYYSQTR.js:411 error loging in Token not found. Call `setLoginToken` first.
```

It works until version 2.1.20. Starting from 2.2.0 I'm getting this error.

I'm using the useExtensionLogin hook:

```
  const [initiateLogin] = useExtensionLogin({
    callbackRoute,
  });
```

The initiateLogin function is called when the user clicks on a button.

**Comment by CiprianDraghici** [comment]
Could you try the lastest version? @multiversx/sdk-dapp@2.3.0

**Comment by CiprianDraghici** [comment]
Closed due to inactivity
