### ISSUE TITLE
Transaction failed on iOS for "testnet" network with "Network Error" "The certificate for this server is invalid".

### ISSUE THREAD

**Issue by Guitarheroua** [multiversx/mx-sdk-dapp#593]
On our web client, we have an issue when trying to run it on iOS. When we send a transaction to our contract, it fails immediately with the following Network error: 

_[Error] Failed to load resource: The certificate for this server is invalid. You might be connecting to a server that is pretending to be "http://testnet-api.elrond.com" which could put your confidential information at risk._

The source code for the transaction is next:

```ts
//NETWORK_ID is just a letter "T"

let tx = contract.methodsExplicit
                .registerDomain([BytesValue.fromUTF8(`${name!}`), new AddressValue(new Address(resolverContractAddress))])
                .withGasLimit(15000000)
                .withChainID(NETWORK_ID )
                .withSingleESDTNFTTransfer(TokenPayment.nonFungible(vaucherId, vaucherNonce!), new Address(address))
                .buildTransaction();

let cx = resolverContract.call({
             func: new ContractFunction('setAddress'),
             gasLimit: 150000000,
             args: [addressValue, BytesValue.fromUTF8(`${name!}`)],
             chainID: NETWORK_ID ,
});

await signTransactions({
             transactions: [tx, cx],
             callbackRoute: pathname,
});

const { sessionId, error } = await sendTransactions({
                transactions: [tx, cx],
                transactionsDisplayInfo: {
                    processingMessage: 'Processing Register transaction',
                    errorMessage: 'An error has occured during Register',
                    successMessage: 'Register transaction successful',
                },
                redirectAfterSign: false,
            });
```

On other systems everything works properly, this issue occurred only on iOS devices(iPad and iPhone)

**Comment by CiprianDraghici** [comment]
Could you try `https://testnet-api.multiversx.com/ `instead of `http://testnet-api.elrond.com/`?

**Comment by Guitarheroua** [comment]
> 

But we do not set this URL, we just set 'chainId' or is it possible to change ot manually. Maybe I missed something.

**Comment by CiprianDraghici** [comment]
What versions you are using for sdk-dapp and sdk-core ?

**Comment by Guitarheroua** [comment]
> @multiversx/sdk-dapp = previously @elrondnetwork/dapp-core @multiversx/sdk-core = previously @elrondnetwork/erdjs

"[@elrondnetwork/dapp-core](https://npmjs.com/package/@elrondnetwork/dapp-core)": "[^2.1.10](https://npmjs.com/package/@elrondnetwork/dapp-core)",
    "[@elrondnetwork/erdjs](https://npmjs.com/package/@elrondnetwork/erdjs)": "[^11.1.1](https://npmjs.com/package/@elrondnetwork/erdjs)",
    "[@elrondnetwork/erdjs-network-providers](https://npmjs.com/package/@elrondnetwork/erdjs-network-providers)": "[^1.1.1](https://npmjs.com/package/@elrondnetwork/erdjs-network-providers)",

**Comment by Guitarheroua** [comment]
> @multiversx/sdk-dapp = previously @elrondnetwork/dapp-core @multiversx/sdk-core = previously @elrondnetwork/erdjs

But we update our packages to new one, just to test if error still occurred, and we also got it, but I could post the text a bit later, do not have access to my computer.

**Comment by Guitarheroua** [comment]
> What versions are you using for sdk-dapp and sdk-core ?

We updated a sdk to latest versions and issue is gone, we got a new one, related to updates, but manage to fix it. Thank you, I will close an issue.
