### ISSUE TITLE
Wallet Connect 2.0 not working when shipping it in production.

### ISSUE THREAD

**Issue by AugustinKimi** [multiversx/mx-sdk-dapp#688]
Hello,

We made the update to the latest version and to handle the new xPortal App connexion but we have trouble making it work.

The integration went well, everything works in local environnement but when shipping it to production or at least on stagging environment, when we scan the QRcode we get the haptic feeback but nothing pop on my mobile. Not error displayed on the mobile screen, no error on the dApp just the QRcode not working.

Does anyone have the same issue ?

Here is the code 

```js
const environment = "mainnet"
const App = () => {
return(
     <DappProvider environment={environment}
    customNetworkConfig={{
      name: 'customConfig',
      walletConnectV2ProjectId: process.env.NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID
    }} >
        <Layout>
          <NotificationModal />
          <SignTransactionsModals />
          <Component {...pageProps} />
        </Layout> 
    </DappProvider>
)
}
```

```jsx
<WalletConnectLoginButton
          callbackRoute="/"
          redirectAfterLogin={false}
          loginButtonText={"Maiar"}
          logoutRoute="/"
          className="wallet-btn wallet-btn-block wallet-btn-connect"
          shouldRenderDefaultCss={false}
          isWalletConnectV2={true}
        >
          <div className="wallet-logo-container">
            <img
              src="/images/walletConnectionIcons/xportal.png"
              alt=""
              className="wallet-logo"
            />
          </div>
          <span className="wallet-name">xPortal App</span>
        </WalletConnectLoginButton>
```

```json
{
  "name": "my-app,
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@multiversx/sdk-core": "^11.4.1",
    "@multiversx/sdk-dapp": "^2.10.3",
    "axios": "^0.27.2",
    "bignumber": "^1.1.0",
    "jsonwebtoken": "^8.5.1",
    "next": "12.2.3",
    "next-transpile-modules": "^10.0.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-modal": "^3.15.1"
  },
  "devDependencies": {
    "eslint": "8.20.0",
    "eslint-config-next": "12.2.3"
  }
}
```

**Comment by AugustinVincent** [comment]
After waiting maybe 2 minutes (Didn't count as it's very long and I usually do something else)

Here is the error : 

```
_app-51c09eaeb85742f4.js:12 Uncaught (in promise) Error: WebSocket connection failed for URL: wss://relay.walletconnect.com?auth=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJkaWQ6a2V5Ono2TWtoaFM5dGJZcWs5ZG5yY2NRWlRFejhLU2tCMVBldXpYRDlGdEdqYktGcDFnciIsInN1YiI6ImRhZDNhNzcyZDY1MWZiYmRlMmQ5OTJiNTFmYjQyNDZhMzI4YTA5MDNmNzM1ZDA0YjBlOTlhMDI4MDVjZmMwMjgiLCJhdWQiOiJ3c3M6Ly9yZWxheS53YWxsZXRjb25uZWN0LmNvbSIsImlhdCI6MTY3ODExMzI4NywiZXhwIjoxNjc4MTk5Njg3fQ.tRCbbYV22Xj4DuQP-X_ATpubF4HlVJuZMLQi9u_KScU3DXMfBE3kOWXaUxGmX7Lrou6kgMlounOM_byc54BeBQ&projectId=f8112c686312233151e350e3fd6b1875&ua=wc-2%2Fjs-2.4.3%2Fmacos-chrome-110.0.0%2Fbrowser%3my-domain.com
    at b6.emitError (_app-51c09eaeb85742f4.js:12:211966)
    at f.onerror (_app-51c09eaeb85742f4.js:12:211229)
    ```

I already tried to setup my domains including the domains i'm testing on, waited 24 hours to make sure eveything is up to date. Nothing worked and now my Allowed Domains are empty.

**Comment by radumojic** [comment]
Hello,

If the issue still persists, this seems like a relayer-specific problem, an invalid `projectId` would theoretically fail instantly.

Are you using a VPN ? That might influence the connection stability sometimes.

As a first step, can you try one of the following region-based relay servers ?

```
// EU
wss://eu-central-1.relay.walletconnect.com

// US
wss://us-east-1.relay.walletconnect.com

// Asia Pacific
wss://ap-southeast-1.relay.walletconnect.com
```

to use a different relay server, you must provide the `walletConnectV2RelayAddresses` array in `customNetworkConfig` on the `<DappProvider>`

something like this:

```jsx
<DappProvider 
  environment={environment}
  customNetworkConfig={{
    name: 'customConfig',
    walletConnectV2ProjectId: process.env.NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID,
    walletConnectV2RelayAddresses: ['wss://eu-central-1.relay.walletconnect.com']
  }}
>
    <Layout>
     ...
    </Layout> 
</DappProvider>
```
  
Also to eliminate any variables, if changing the relay server doesn't work, can you make a test with the following `projectId` ?

`9b1a9564f91cb659ffe21b73d5c4e2d8`

It's the one used on [https://github.com/multiversx/mx-template-dapp](https://github.com/multiversx/mx-template-dapp), not recommended for production use, but it should work for a short test.

**Comment by AugustinVincent** [comment]
None of the above solutions worked.

I'm not using a VPS. (Domains are managed by vercel)

Setting the walletConnectV2RelayAddresses doesn't work

Using this projectId : 9b1a9564f91cb659ffe21b73d5c4e2d8 doesn't work either.

**Comment by radumojic** [comment]
Seems that you might have a corrupted WC2 state

Can you try clearing the Local Storage before trying again ?
WC2 saves it's current state in Local Storage with keys prefixed by '`wc@2:`', maybe something went wrong there and each time it tries to reinitialize, it fails because of that corrupted state.

Also, useful for debugging, you can add `walletConnectV2Options: { logger: 'debug' }` to the `customNetworkConfig` and that would give you a full WC2 debugging flow in the console, maybe that helps narrowing it down

**Comment by radumojic** [comment]
Can you scan the QR code and login using https://react-wallet.walletconnect.com/ ?

It's the default implementation for a WalletConnect 2.0 signing app from WalletConnect
See more here: https://github.com/WalletConnect/web-examples

This should show you a preview of all the methods used on login.

Something like this:
![IMG_3914](https://user-images.githubusercontent.com/74196626/225101825-d342794f-4f64-4db8-bda1-4cdf099c154e.jpg)

**Comment by AugustinVincent** [comment]
Scanning the QRcode with this seems to work. It trigger the permissions. The methods are exactly the same.

On my side it seems to work, I get a response every hooks I'm using from @multiversx/sdk-dapp works well.


erd15j4hute3gd4s4pwazh8duscmdp5qt3fcj8mtjwaqtjlvyr0z8tyqryc2s6
--
?auth=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpc3M…ows10-chrome-111.0.0%2Fbrowser%3Alocalhost%3A3000
config
?address=erd15j4hute3gd4s4pwazh8duscmdp5qt3fcj8mtj…vyr0z8tyqryc2s6&EIO=4&transport=polling&t=ORXagQg
?address=erd15j4hute3gd4s4pwazh8duscmdp5qt3fcj8mtj…nsport=polling&t=ORXagSI&sid=uUwk66Jk4fHrBBYQAHJq
?address=erd15j4hute3gd4s4pwazh8duscmdp5qt3fcj8mtj…nsport=polling&t=ORXagSJ&sid=uUwk66Jk4fHrBBYQAHJq
?address=erd15j4hute3gd4s4pwazh8duscmdp5qt3fcj8mtj…nsport=polling&t=ORXagSq&sid=uUwk66Jk4fHrBBYQAHJq
?address=erd15j4hute3gd4s4pwazh8duscmdp5qt3fcj8mtj…IO=4&transport=websocket&sid=uUwk66Jk4fHrBBYQAHJq
config
erd15j4hute3gd4s4pwazh8duscmdp5qt3fcj8mtjwaqtjlvyr0z8tyqryc2s6
erd15j4hute3gd4s4pwazh8duscmdp5qt3fcj8mtjwaqtjlvyr0z8tyqryc2s6
erd15j4hute3gd4s4pwazh8duscmdp5qt3fcj8mtjwaqtjlvyr0z8tyqryc2s6

Here is all the request in the request tab once I approved the login in case you need it.

**Comment by raress96** [comment]
I have something similar although I am not sure if it is the same issue.

I can scan the code/click the link on mobile, but in xPortal I just get a loading screen. BUT I am logged in on the website if I hit back in xPortal, although xPortal doesn't have any connection open.

And when I initiate a transaction, it works as expected and I can sign it through xPortal and then send it through the dApp, which is super weird...

**Comment by AugustinVincent** [comment]
It cannot be from my devices, there is a whole community that cannot use this connection and we've been forced to delete this login method for a moment. 

I'll take time to fill it

When I do it directly on my devices by clicking the button it doesn't work either.

**Comment by AugustinKimi** [comment]
@radumojic Any news. Why do I feel like my issue is getting ignored ? No response for 2 weeks now, on discord neither.

Will finally have to move our entire tools to other package....

**Comment by damienen** [comment]
many users also have issues with connecting on many dApps that are using sdk-dapps since the release of xPortal

**Comment by radumojic** [comment]
The latest release ( `@multiversx/sdk-dapp@2.10.17` ) should address some connection and stability issues on  WalletConnect, we also updated the @walletconnect libraries to their latest versions.

As the `@walletconnect` project is constantly improving, we will try to keep up with the latest releases that improve the speed and the websocket connection liveness.

Also, xPortal received some significant updates recently on both iOS and Android that should further improve the connection stability and fix some previous issues.

Can you try out the latest versions and see if they fix the issues ?

**Comment by damienen** [comment]
Wow! Just upgraded two of my dApps to 2.10.17 and xPortal login is way
smoother.

Thank you!

**Comment by schimih** [comment]
Hey @AugustinKimi 

Did you have time to check if they fixed the issues?

:pray:

**Comment by CiprianDraghici** [comment]
Closed due to inactivity
