### ISSUE TITLE
Trying to sign a message with Web Wallet does not work

### ISSUE THREAD

**Issue by damienen** [multiversx/mx-sdk-dapp#733]
Here's a video with the tried flow:
https://www.loom.com/share/c4d546032ff34693afdf772e537f8018

These are all the MX libraries we use in our project:
"@multiversx/sdk-core": "12.1.1",
"@multiversx/sdk-dapp": "2.11.2",
"@multiversx/sdk-network-providers": "1.4.0",
"@multiversx/sdk-transaction-decoder": "1.0.2",

Other packages that might be relevant:
"react": "18.2.0",
"react-dom": "18.2.0"
"engines": {"node": "18.15.0"}
 
Env:
Google Chrome - Version 112.0.5615.122 (Official Build) (64-bit)
Windows 11 Home 10.0.22621 Build 22621
Samsung 960XFH
 
The code snippet:
https://github.com/Itheum/data-dex/blob/e0449cdadbbdb32fc5666369289aeafd0aa7c896/src/DataNFT/WalletDataNFTMX.tsx#L134
 
Note: changed from walletUsedSession === "el_webwallet" to walletUsedSession !== "el_webwallet" locally in order to test web wallet for signing (we have disabled it in production for now)

**Comment by andreibancioiu** [comment]
Normally, this should be fixed if `sdk-dapp` references a `web-wallet-provider` that is newer than `v2.3.0`.

For reference: https://github.com/multiversx/mx-sdk-js-web-wallet-provider/pull/19

**Comment by arhtudormorar** [comment]
Can you try to follow [the template-dapp](https://github.com/multiversx/mx-template-dapp/blob/main/src/pages/SignMessage/SignMessage.tsx
) example?:
, and check the functionality [here](https://template-dapp.multiversx.com/sign-message
):
