### ISSUE TITLE
If a user is logged in by providing a nativeAuth token via accessToken query parameter, logout is not working

### ISSUE THREAD

**Issue by damienen** [multiversx/mx-sdk-dapp#935]
We are keen to implement a way for our users to automatically login when they move from one of our websites to another one by propagating an accessToken.

One issue when we log them in this way is that the sdk-dapp logout util function does not work

**Comment by CiprianDraghici** [comment]
This is not an issue, but the actual behavior. The concept was implemented with a dedication to xPortal Hub to prevent the logout when the user opens the dApp from the Hub. But, also for other use-cases (like yours), there is a way to prevent this default behavior.  You should set the `shouldAttemptRelogin` option to `false` when the logout function is called:

`logout(`${window.location.origin}`, undefined, false);`

**Comment by damienen** [comment]
This answer clarifies it. Closing. Thank you!
